// src/components/Navbar.vue
<script setup lang="ts">
// vue
import { ref, computed } from 'vue';

// icons
import IconMenuList from './icons/IconList.vue';
import IconMenuX from './icons/IconX.vue';
import IconFacebook from './icons/Facebook.vue';
import IconLinkIn from './icons/LinkIn.vue';
import IconGithub from './icons/Github.vue';

const isOpen = ref(false);
const toggleList = ref(true);
const toggleX = ref(false);

const toggleMenu = () => {
	isOpen.value = !isOpen.value;
	toggleList.value = !toggleList.value;
	toggleX.value = !toggleX.value;
};

const menuClass = computed(() => {
	return isOpen.value ? 'left-0' : '-left-[200%]';
});
</script>

<template>
	<div class="navbar sticky top-3 md:mx-4 lg:mx-6">
		<div
			class="relative flex justify-between items-center my-3 mx-2 p-3 inset-shadow-sm shadow-md rounded-full bg-white md:py-3 lg:max-w-7xl lg:mx-auto"
		>
			<!-- logo -->
			<div class="font-semibold text-xl">DYR.</div>
			<!-- menu -->
			<ul
				:class="`${menuClass} absolute flex justify-center items-center gap-5 py-9 top-16 w-full bg-white inset-shadow-sm shadow-md rounded-lg transition-all duration-500 md:left-0 md:top-0 md:relative md:py-0 md:text-lg md:gap-7 md:shadow-none md:inset-shadow-none md:bg-transparent lg:gap-10`"
			>
				<li class="text-orange-600">
					<a href="#home" @click="toggleMenu">Home</a>
				</li>
				<li class="hover:text-orange-600">
					<a href="#about" @click="toggleMenu">About</a>
				</li>
				<li class="hover:text-orange-600">
					<a href="#">Project</a>
				</li>
				<li class="hover:text-orange-600">
					<a href="#">Contact</a>
				</li>
			</ul>
			<div class="flex items-center gap-4">
				<!-- sosial -->
				<ul class="flex items-center gap-3">
					<li>
						<a href="#" class="text-xl"><IconFacebook /></a>
					</li>
					<li>
						<a href="#" class="text-xl"><IconLinkIn /></a>
					</li>
					<li>
						<a href="#" class="text-xl"><IconGithub /></a>
					</li>
				</ul>
				<!-- mobile toggle -->
				<div class="flex items-center md:hidden">
					<button @click="toggleMenu" class="text-2xl cursor-pointer" v-show="toggleList"><IconMenuList /></button>
					<button @click="toggleMenu" class="text-2xl cursor-pointer" v-show="toggleX"><IconMenuX /></button>
				</div>
			</div>
		</div>
	</div>
</template>

// components/Navbar.tsx
'use client';

import { menuNavbar } from '@/data';
import Link from 'next/link';
import { useState } from 'react';
import { FaSquareGithub } from 'react-icons/fa6';
import { FaSquareFacebook } from 'react-icons/fa6';
import { FaLinkedin } from 'react-icons/fa6';
import { VscListSelection } from 'react-icons/vsc';
import { LiaTimesSolid } from 'react-icons/lia';
import useDetecScrolled from '@/hooks/detect-scrolled';
import useDetectSize from '@/hooks/detect-size';

const Navbar = () => {
	const [isOpen, setIsOpen] = useState(false);

	const isScrolled = useDetecScrolled();
	const sizeIcon = useDetectSize({
		minSize: 20,
		maxSize: 25,
		width: 768,
	});

	const handleToggle = () => {
		setIsOpen(!isOpen);
	};

	return (
		<nav className="sticky top-0 z-50 py-5">
			<div
				className={`flex items-center justify-between border rounded-full py-3 px-4 ${
					isScrolled ? 'bg-neutral-950' : ''
				}`}
			>
				{/* logo */}
				<div className="logo">
					<h1 className="text-xl font-bold text-transparent bg-clip-text bg-gradient-to-b from-neutral-200 to-neutral-600">
						DYR
					</h1>
				</div>

				{/* list menu */}
				<div
					className={`listMenu fixed top-[80px] bg-background w-full py-6 px-4 transition-all duration-500 ease-in-out md:static md:top-auto md:left-auto md:bg-transparent md:p-0 ${
						isOpen ? 'left-0' : '-left-full'
					}`}
				>
					<ul className="flex items-center justify-center gap-4">
						{menuNavbar.map((menu) => (
							<li key={menu.id}>
								<Link
									href={menu.link}
									className="text-base font-semibold text-transparent bg-clip-text bg-gradient-to-b from-neutral-200 to-neutral-600 lg:text-lg"
								>
									{menu.name}
								</Link>
							</li>
						))}
					</ul>
				</div>

				{/* icon socialmedia */}
				<div className="social-media flex items-center gap-2">
					<Link href="#">
						<FaSquareFacebook size={sizeIcon} className="text-neutral-400" />
					</Link>
					<Link href="#">
						<FaSquareGithub size={sizeIcon} className="text-neutral-400" />
					</Link>
					<Link href="#">
						<FaLinkedin size={sizeIcon} className="text-neutral-400" />
					</Link>

					{/* toggle mobile */}
					<button onClick={handleToggle} className="menu-toggle ml-4 md:hidden">
						{isOpen ? (
							<LiaTimesSolid size={20} className="text-neutral-400" />
						) : (
							<VscListSelection size={20} className="text-neutral-400" />
						)}
					</button>
				</div>
			</div>
		</nav>
	);
};

export default Navbar;
